In [2]:
#how to reshape the array
import numpy as np
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(ar)
print(ar.ndim)
print(ar.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
(12,)


In [9]:
nar=ar.reshape(4,3)
print(nar)
print(nar.ndim)
print(nar.shape)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)


In [10]:
nar=ar.reshape(3,4)
print(nar)
print(nar.ndim)
print(nar.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [12]:
nar=ar.reshape(2,3,2)
print(nar)
print(nar.ndim)
print(nar.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [29]:
nar=ar.reshape(1,1,1,2,3,2)
print(nar)
print(nar.ndim)
print(nar.shape)

[[[[[[ 1  2]
     [ 3  4]
     [ 5  6]]

    [[ 7  8]
     [ 9 10]
     [11 12]]]]]]
6
(1, 1, 1, 2, 3, 2)


In [43]:
#convert 1 d array with 8 elements to the 2X2 elements
ar= np.array([i for i in range(1,9)])
nar=ar.reshape(2,2,)-1
print(nar.ndim)
print(nar)
print(nar.shape)

ValueError: cannot reshape array of size 8 into shape (2,2)

In [46]:
ar=np.array([1,2,3,4,5])
x=ar.copy()
x2=ar
x1=ar.view()
ar[0]=100
x1[1]=1000
x2[3]=1000
print(ar)
print(x)
print(x1)
print(x2)

[ 100 1000    3 1000    5]
[1 2 3 4 5]
[ 100 1000    3 1000    5]
[ 100 1000    3 1000    5]


In [61]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a=np.concatenate((a1,a2))
print(a)
print(np.stack((a1,a2),axis=1))
print(np.stack((a1,a2)))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
